import { Injectable } from '@angular/core';
import { CardComponent } from '../app/components/card/card.component';
import { EbookModel } from '../models/ebook.model';
import { CategoryModel } from '../models/category.model';

/** Constants used to fill up our data base. */
export const GENRES: string[] = [
  'Adventure',
  'Science Fiction',
  'Fantasy',
  'Mystery',
  'Historical Fiction',
  'Horror',
  'Thriller',
  'Romance',
  'Westerns',
  'Dystopian',
  'Memoir',
  'Biography',
  'Self-help',
  'Cookbooks',
  'History',
  'Travel',
  'True Crime',
  'Humor',
  'Children’s',
  'Young Adult',
  'Poetry',
  'Science',
  'Nature',
  'Math',
  'Philosophy',
  'Religion',
  'Spirituality',
  'New Age',
  'Art',
  'Photography',
  'Architecture',
  'Music',
  'Film',
  'Fashion',
  'Performing Arts',
  'Graphic Novels',
  'Manga',
];
export const NAMES: string[] = [
  'Around the World in Eighty Days',
  'The War of the Worlds',
  'The Time Machine',
  'The Invisible',
  'The Island of Doctor Moreau',
  'The First',
  'The Lost World',
  'The Call of the Wild',
  'The Picture of Dorian Gray',
  'The Adventures of Sherlock Holmes',
  'The Hound of the Baskervilles',
  'The Sign of the Four',
  'The Valley of Fear',
  'The Adventures of Tom Sawyer',
  'The Adventures of Huckleberry Finn',
  'The Prince and the Pauper',
  "A Connecticut Yankee in King Arthur's Court",
  "The Tragedy of Pudd'nhead Wilson",
  'The Innocents Abroad',
  'Roughing It',
  'The Gilded Age',
  'A Tramp Abroad',
  'Life on the Mississippi',
  'Alice in Wonderland',
  'Through the Looking Glass',
  'The Hunting of the Snark',
  'The Secret Garden',
  'A Little Princess',
  'Little Lord Fauntleroy',
  'The Lost Prince',
  'The Railway Children',
  'Five Children and It',
  'The Phoenix and the Carpet',
  'The Story of the Amulet',
  'The Enchanted Castle',
  'Hard Times',
  'Great Expectations',
  'A Christmas Carol',
  'Oliver Twist',
  'David Copperfield',
  'Bleak House',
  'Little Dorrit',
  'The Pickwick Papers',
  'Our Mutual Friend',
  'The Old Curiosity Shop',
  'Nicholas Nickleby',
  'Martin Chuzzlewit',
  'Dombey and Son',
  'The Mystery of Edwin Drood',
  'The Chimes',
  'The Cricket on the Hearth',
  'The Battle of Life',
  'The Ha',
  'Gone with the Wind',
  'The Great Gatsby',
  'To Kill a Mockingbird',
  'The Catcher in the Rye',
  'The Grapes of Wrath',
  'The Lord of the Rings',
  'The Hobbit',
  'The Silmarillion',
  'The Two Towers',
  'The Return of the King',
  'The Fellowship of the Ring',
  'The Adventures of Huckleberry Finn',
  'The Good Earth',
  'The Sun Also Rises',
  'The Old',
  'The Godfather',
  'The Godfather Returns',
  "The Godfather's Revenge",
  "Harry Potter and the Philosopher's Stone",
  'Harry Potter and the Chamber of Secrets',
  'Harry Potter and the Prisoner of Azkaban',
  'Harry Potter and the Goblet of Fire',
  'Harry Potter and the Order of the Phoenix',
  'Harry Potter and the Half-Blood Prince',
  'Harry Potter and the Deathly Hallows',
  'The Da Vinci Code',
  'Angels & Demons',
  'The Lost Symbol',
  'Inferno',
  'Origin',
  'Digital Fortress',
  'Deception Point',
  'The Hunger Games',
  'Catching Fire',
  'Mockingjay',
  'The Ballad of Songbirds and Snakes',
  'The Maze Runner',
  'The Scorch Trials',
  'The Death Cure',
  'The Kill Order',
  'The Fever Code',
  'The Outsiders',
  'That Was Then, This Is Now',
  'Rumble Fish',
  'Tex',
  'Taming the Star Runner',
  'Holes',
  'Small Steps',
  'Wayside School is Falling Down',
  'Wayside School Gets a Little Stranger',
  'Sideways Stories from Wayside School',
  'The Giver',
  'Gathering Blue',
  'Messenger',
  'Son',
  'Number the Stars',
  'Anastasia Krupnik',
  'The Giver',
  'Finale',
  'Caraval',
  'Shatter Me',
  'Restore Me',
  'Ignite Me',
  'Unravel Me',
  'Defy Me',
  'Destroy Me',
  'The Selection',
  'The Elite',
  'The One',
  'The Heir',
  'The Crown',
  'The Prince',
  'The Guard',
  'The Queen',
  'The Favorite',
  'The Siren',
  'The Betrothed',
  'The Traitor',
  'The Queen of Nothing',
  'The Wicked King',
  'The Cruel Prince',
  'The Lost Sisters',
  'The Darkest Part of the Forest',
  'The Col',
  'Green Eggs and Ham',
  'The Cat in the Hat',
  'One Fish Two Fish Red Fish Blue Fish',
  'Horton Hears a Who!',
  'How the Grinch Stole Christmas!',
  'Fox in Socks',
  'The Lorax',
  'Oh, the Places You’ll Go!',
  'The Sneetches and Other Stories',
  'Dr. Seuss’s Sleep Book',
  'Hop on Pop',
  'Scrambled Eggs Super!',
  'The Butter Battle Book',
  'I Had Trouble in Getting to Solla Sollew',
  'If I Ran the Circus',
  'If I Ran the Zoo',
  'The 500 Hats of Bartholomew Cubbins',
  'The King’s Stilts',
  'McElligot’s Pool',
  'On Beyond Zebra!',
  'Thidwick the Big-Hearted Moose',
  'Yertle the Turtle and Other Stories',
  'Bartholomew and the Oobleck',
  'Daisy-Head Mayzie',
  'Did I Ever Tell You How Lucky You Are?',
  'Dr. Seuss’s ABC',
  'Gerald McBoing Boing',
  'Happy Birthday to You!',
  'Horton Hatches the Egg',
];
export const AUTHORS: string[] = [
  'Jules Verne',
  'H.G. Wells',
  'Oscar Wilde',
  'Arthur Conan Doyle',
  'Mark Twain',
  'Frances Hodgson Burnett',
  'Charles Dickens',
  'Margaret Mitchell',
  'F. Scott Fitzgerald',
  'Harper Lee',
  'J.R.R. Tolkien',
  'John Steinbeck',
  'Mario Puzo',
  'J.K. Rowling',
  'Dan Brown',
  'Suzanne Collins',
  'James Dashner',
  'S.E. Hinton',
  'Lois Lowry',
  'Stephanie Garber',
  'Tahereh Mafi',
  'Kiera Cass',
];

@Injectable({
  providedIn: 'root',
})
export class CardService {
  cards: EbookModel[] = [
    {
      id: '1',
      title: 'The Hobbit',
      author: 'J. R. R. Tolkien',
      detail:
        "The Hobbit is the unforgettable story of Bilbo, a peace-loving hobbit, who embarks on a strange and magical adventure. A timeless classic. Bilbo Baggins enjoys a quiet and contented life, with no desire to travel far from the comforts of home; then one day the wizard Gandalf and a band of dwarves arrive unexpectedly and enlist his services - as a burglar - on a dangerous expedition to raid the treasure-hoard of Smaug the dragon. Bilbo's life is never to be the same again. Seldom has any book been so widely read and loved as J. R.R. Tolkien's classic tale, 'The Hobbit'. Since its first publication in 1937 it has remained in print to delight each new generation of readers all over the world, and its hero, Bilbo Baggins, has taken his place among the ranks of the immortals of fiction.",
      image: 'public/assets/books-img/theHobbit.png',
      date: '06/07/2012',
      view: 100,
      like: 50,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '2',
      title: 'Azathoth',
      author: 'H.P. Lovecraft',
      detail:
        'When age fell upon the world, and wonder went out of the minds of men; when grey cities reared to smoky skies tall towers grim and ugly, in whose shadow none might dream of the sun or of spring’s flowering meads; when learning stripped earth of her mantle of beauty, and poets sang no more save of twisted phantoms seen with bleared and inward-looking eyes; when these things had come to pass, and childish hopes had gone away forever, there was a man who travelled out of life on a quest into the spaces whither the world’s dreams had fled.',
      image: 'public/assets/books-img/azathoth.png',
      date: '8/20/2009',
      view: 200,
      like: 100,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '3',
      title: 'The Charm Offensive',
      author: 'Alison Cochrun',
      detail:
        'Dev Deshpande has always believed in fairy tales. So it’s no wonder then that he’s spent his career crafting them on the long-running reality dating show Ever After. As the most successful producer in the franchise’s history, Dev always scripts the perfect love story for his contestants, even as his own love life crashes and burns. But then the show casts disgraced tech wunderkind Charlie Winshaw as its star.',
      image: 'public/assets/books-img/theCharmOffensive.png',
      date: '2021',
      view: 300,
      like: 150,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '4',
      title: 'The God Of The Woods',
      author: 'Liz Moore',
      detail:
        'Early morning, August 1975: a camp counselor discovers an empty bunk. Its occupant, Barbara Van Laar, has gone missing. Barbara isn’t just any thirteen-year-old: she’s the daughter of the family that owns the summer camp and employs most of the region’s residents. And this isn’t the first time a Van Laar child has disappeared. Barbara’s older brother similarly vanished fourteen years ago, never to be found.',
      image: 'public/assets/books-img/theGodOfTheWoods.png',
      date: 'July 2, 2024',
      view: 400,
      like: 200,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '5',
      title: 'What Is History?',
      author: 'E.H. Carr',
      detail:
        'Who is to say how things really were? In formulating a modern answer to the question ‘What is History?’ Professor Carr shows that the ‘facts’ of history are simply those which historians have selected for scrutiny. Millions have crossed the Rubicon, but the historians tell us that only Caesar’s crossing was significant. All historical facts come to us as a result of interpretative choices by historians influenced by the standards of their age. Yet if absolute objectivity is impossible, the role of the historian need in no way suffer; nor does history lose its fascination. With lucidity, Carr casts a light on the proper function of the historian and the vital importance of history in modern society. -- Provided by publisher',
      image: 'public/assets/books-img/whatIsHistory.png',
      date: ' 1961',
      view: 500,
      like: 250,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '6',
      title: 'The Invisible Hand',
      author: 'Adam Smith',
      detail:
        'Adam Smith’s landmark treatise on the free market paved the way for modern capitalism, arguing that competition is the engine of a productive society, and that self-interest will eventually come to enrich the whole community, as if by an ‘invisible hand’. Throughout history, some books have changed the world. They have transformed the way we see ourselves – and each other. They have inspired debate, dissent, war and revolution. They have enlightened, outraged, provoked and comforted. They have enriched lives – and destroyed them. Now Penguin brings you the works of the great thinkers, pioneers, radicals and visionaries whose ideas shook civilization and helped make us who we are.',
      image: 'public/assets/books-img/theInvisibleHand.png',
      date: 'January 1, 1759',
      view: 600,
      like: 300,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '7',
      title: 'The Wonderful Things You Will Be',
      author: 'E.W Martin',
      detail:
        'The New York Times bestseller that celebrates the dreams, acceptance, and love that parents have for their children . . . now and forever. This is the perfect heartfelt gift for kids of all ages, plus a great choice for baby showers, birthdays, graduations, and other new beginnings!',
      image: 'public/assets/books-img/theWonderfulThingsYouWillBe.png',
      date: 'August 25, 2015',
      view: 700,
      like: 350,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '8',
      title: 'Be Smart Investor',
      author: 'Warren Buffet',
      detail:
        'The greatest investment advisor of the twentieth century, Benjamin Graham, taught and inspired people worldwide. Graham\'s philosophy of "value investing" -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible ever since its original publication in 1949.',
      image: 'public/assets/books-img/beSmartInvestor.png',
      date: 'February 21, 2006',
      view: 800,
      like: 400,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '9',
      title: 'Hamlet',
      author: 'William Shakespeare',
      detail:
        'Among Shakespeare\'s plays, "Hamlet" is considered by many his masterpiece. Among actors, the role of Hamlet, Prince of Denmark, is considered the jewel in the crown of a triumphant theatrical career. Now Kenneth Branagh plays the leading role and co-directs a brillant ensemble performance. Three generations of legendary leading actors, many of whom first assembled for the Oscar-winning film "Henry V", gather here to perform the rarely heard complete version of the play. This clear, subtly nuanced, stunning dramatization, presented by The Renaissance Theatre Company in association with "Bbc" Broadcasting, features such luminaries as Sir John Gielgud, Derek Jacobi, Emma Thompson and Christopher Ravenscroft. It combines a full cast with stirring music and sound effects to bring this magnificent Shakespearen classic vividly to life. Revealing new riches with each listening, this production of "Hamlet" is an invaluable aid for students, teachers and all true lovers of Shakespeare - a recording to be treasured for decades to come.',
      image: 'public/assets/books-img/Hamlet.png',
      date: '1603',
      view: 900,
      like: 450,
      pdf: '',
      categories: this.genCategories(),
    },
    {
      id: '10',
      title: 'The Odyssey',
      author: 'Homer',
      detail:
        'Sing to me of the man, Muse, the man of twists and turns\n' +
        'driven time and again off course, once he had plundered\n' +
        'the hallowed heights of Troy.',
      image: 'public/assets/books-img/theOdyssey.png',
      date: '8th century BC',
      view: 1000,
      like: 500,
      pdf: '',
      categories: this.genCategories(),
    },
  ];

  constructor() {}

  genCategories(): CategoryModel[] {
    const categories: CategoryModel[] = [];
    const num = Math.round(Math.random() * 5);
    for (let i = 0; i < num; i++) {
      categories.push({
        id: i.toString(),
        name: GENRES[Math.round(Math.random() * (GENRES.length - 1))],
      });
    }
    return categories;
  }

  /** Builds and returns a new User. */
  createNewEbook(id: number): EbookModel {
    const name =
      NAMES[Math.round(Math.random() * (NAMES.length - 1))] +
      ' ' +
      NAMES[Math.round(Math.random() * (NAMES.length - 1))].charAt(0) +
      '.';

    //random genre and number of genre from GENRES

    return {
      id: id.toString(),
      title: name,
      author: AUTHORS[Math.round(Math.random() * (AUTHORS.length - 1))],
      detail: 'This is a detail of ' + name,
      image: 'public/assets/books-img/Emma-Jane-Austen.jpg',
      date: new Date().toDateString(),
      view: Math.round(Math.random() * 1000),
      like: Math.round(Math.random() * 100),
      pdf: 'public/assets/pdfs/Bootstrap-vs-Material-Design-vs-Prime-vs-Tailwind.pdf',
      categories: this.genCategories(),
    };
  }

  initCategorylist(): CategoryModel[] {
    const categories: CategoryModel[] = [];
    for (let i = 0; i < GENRES.length; i++) {
      categories.push({
        id: i.toString(),
        name: GENRES[i],
      });
    }
    return categories;
  }
}
