import { Injectable } from '@angular/core';
import { CardComponent } from '../app/components/card/card.component';
import { EbookModel } from '../models/ebook.model';

@Injectable({
  providedIn: 'root',
})
export class CardService {
  cards: EbookModel[] = [
    {
      id: '1',
      title: 'Book 1',
      author: 'Author 1',
      detail: 'Detail 1',
      image: 'public/assets/books-img/Book1.png',
      date: '2023',
      view: 100,
      like: 50,
      pdf: '',
      genre: ['Fiction'],
    },
    {
      id: '2',
      title: 'Book 2',
      author: 'Author 2',
      detail: 'Detail 2',
      image: 'public/assets/books-img/Book2.png',
      date: '2023',
      view: 200,
      like: 100,
      pdf: '',
      genre: ['Non-Fiction'],
    },
    {
      id: '3',
      title: 'Book 3',
      author: 'Author 3',
      detail: 'Detail 3',
      image: 'public/assets/books-img/Book3.png',
      date: '2023',
      view: 300,
      like: 150,
      pdf: '',
      genre: ['Science'],
    },
    {
      id: '4',
      title: 'Book 4',
      author: 'Author 4',
      detail: 'Detail 4',
      image: 'public/assets/books-img/Book4.png',
      date: '2023',
      view: 400,
      like: 200,
      pdf: '',
      genre: ['History'],
    },
    {
      id: '5',
      title: 'Book 5',
      author: 'Author 5',
      detail: 'Detail 5',
      image: 'public/assets/books-img/Book5.png',
      date: '2023',
      view: 500,
      like: 250,
      pdf: '',
      genre: ['Biography'],
    },
    {
      id: '6',
      title: 'Book 6',
      author: 'Author 6',
      detail: 'Detail 6',
      image: 'public/assets/books-img/Book6.png',
      date: '2023',
      view: 600,
      like: 300,
      pdf: '',
      genre: ['Fantasy'],
    },
    {
      id: '7',
      title: 'Book 7',
      author: 'Author 7',
      detail: 'Detail 7',
      image: 'public/assets/books-img/Book1.png',
      date: '2023',
      view: 700,
      like: 350,
      pdf: '',
      genre: ['Mystery'],
    },
    {
      id: '8',
      title: 'Book 8',
      author: 'Author 8',
      detail: 'Detail 8',
      image: 'public/assets/books-img/Book2.png',
      date: '2023',
      view: 800,
      like: 400,
      pdf: '',
      genre: ['Romance'],
    },
    {
      id: '9',
      title: 'Book 9',
      author: 'Author 9',
      detail: 'Detail 9',
      image: 'public/assets/books-img/Book3.png',
      date: '2023',
      view: 900,
      like: 450,
      pdf: '',
      genre: ['Thriller'],
    },
    {
      id: '10',
      title: 'Book 10',
      author: 'Author 10',
      detail: 'Detail 10',
      image: 'public/assets/books-img/Book4.png',
      date: '2023',
      view: 1000,
      like: 500,
      pdf: '',
      genre: ['Adventure'],
    },
  ];

  constructor() {}
}
